export const GRADIENT_ADD_NEW_ITEM = 'GRADIENT_ADD_NEW_ITEM';
export const GRADIENT_DELETE_ITEM = 'GRADIENT_DELETE_ITEM';
export const GRADIENT_MODIFY_ITEM = 'GRADIENT_MODIFY_ITEM';
export const GRADIENT_CHANGE_CURRENT = 'GRADIENT_CHANGE_CURRENT';
export const GRADIENT_CLEAR_CURRENT = 'GRADIENT_CLEAR_CURRENT';
